apiVersion: v1
kind: Service
metadata:
  name: spekt8-svc
spec:
  ports:
  - port: 30333
    protocol: TCP
    targetPort: 3000
    nodePort: 30333
  selector:
    component: spekt8-v2
  type: NodePort
